// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyPEoWk0C7gSN6oObO8-KVagT32_2B87o',
    appId: '1:73253916918:web:6df42fd4b35358d87f9cd7',
    messagingSenderId: '73253916918',
    projectId: 'glucolife-13b84',
    authDomain: 'glucolife-13b84.firebaseapp.com',
    storageBucket: 'glucolife-13b84.appspot.com',
    measurementId: 'G-XQ05SPD7LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvfJ7mTBiczZrg-wx3BM3MfD6cJ1CyfWo',
    appId: '1:73253916918:android:d26947c27dec9ecb7f9cd7',
    messagingSenderId: '73253916918',
    projectId: 'glucolife-13b84',
    storageBucket: 'glucolife-13b84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAp9cA1gVYWJwIUWwpVoNv8zvh2Ry33cxQ',
    appId: '1:73253916918:ios:481c54f3464518647f9cd7',
    messagingSenderId: '73253916918',
    projectId: 'glucolife-13b84',
    storageBucket: 'glucolife-13b84.appspot.com',
    iosBundleId: 'com.example.glucolifeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAp9cA1gVYWJwIUWwpVoNv8zvh2Ry33cxQ',
    appId: '1:73253916918:ios:767a5b640e3d4f727f9cd7',
    messagingSenderId: '73253916918',
    projectId: 'glucolife-13b84',
    storageBucket: 'glucolife-13b84.appspot.com',
    iosBundleId: 'com.example.glucolifeApp.RunnerTests',
  );
}
