// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB6If5PM7gYKhoIpFytA5tD_4AjjZ0GOM',
    appId: '1:225272454831:web:593113925d7853997afe5a',
    messagingSenderId: '225272454831',
    projectId: 'glucolife-d0108',
    authDomain: 'glucolife-d0108.firebaseapp.com',
    storageBucket: 'glucolife-d0108.appspot.com',
    measurementId: 'G-B5P95LS6YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTZy6KTm7Y4zn_oGqj7o52-zkx0hTj4V0',
    appId: '1:225272454831:android:9a8889e59a8913257afe5a',
    messagingSenderId: '225272454831',
    projectId: 'glucolife-d0108',
    storageBucket: 'glucolife-d0108.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqX8aT7X8v-AtsRrjDGzCxKnPm77zpSfc',
    appId: '1:225272454831:ios:edd794449665f3137afe5a',
    messagingSenderId: '225272454831',
    projectId: 'glucolife-d0108',
    storageBucket: 'glucolife-d0108.appspot.com',
    iosBundleId: 'com.example.glucolifeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqX8aT7X8v-AtsRrjDGzCxKnPm77zpSfc',
    appId: '1:225272454831:ios:85779505618827747afe5a',
    messagingSenderId: '225272454831',
    projectId: 'glucolife-d0108',
    storageBucket: 'glucolife-d0108.appspot.com',
    iosBundleId: 'com.example.glucolifeApp.RunnerTests',
  );
}
